import type { Metadata } from "next";
import localFont from "next/font/local";
import "./styles/globals.css";
import { Noto_Sans_KR} from 'next/font/google';
import './styles/main.scss';
import { Toaster } from "@/components/ui";

const noto = Noto_Sans_KR({
  subsets: ['latin'],
  display: "swap",
})

/*const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});*/

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={noto.className} >
        {children}
        <Toaster/>
      </body>
    </html>
  );
}
