import type { Metadata } from "next";
import "./styles/globals.css"
import { Noto_Sans_KR} from 'next/font/google';
import './styles/main.scss';
import { Toaster } from "@/components/ui";

const noto = Noto_Sans_KR({
  subsets: ['latin'],
  display: "swap",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={noto.className} >
        {children}
        <Toaster/>
      </body>
    </html>
  );
}

